### PR TITLE
Fix SVG scaling issue in IE

### PR DESCRIPTION
**Pull request by Sambillingham**
:exclamation: Not fixed yet. Looking into fixing #65 

used the bash script in at - https://gist.github.com/larrybotha/7881691

```bash
find ./ -name '*.svg' -print0 | xargs -0 sed -i "" -e 's/width="[0-9]*\.*\[0-9]*" //' -e 's/height="[0-9]*\.*\[0-9]*" //'
```

But it only modified this set of images which does not include those that look broken in the screenshot in #65 so cannot of fixed all of the issues. 
```
modified:   icon-github.svg
modified:   icon-link.svg
modified:   icon-twitter.svg
modified:   speaker-coming-soon-bottom.svg
modified:   sponsor-code-first-girls.svg
modified:   sponsor-makers-academy.svg
modified:   sponsor-moo.svg
```

The CSS approach listed in the same gist above might be the next best approach. Also trying something like https://github.com/svg/svgo to optimise and trip out all the fluff in the SVGs might help. There is a gulp tasks that uses svgo too. Maybe test it works first though

### CODE REVIEW

**Comment by Sambillingham** [comment]
Nicely done. Pulled it down and fired it through browserstack. LGTM

**Comment by Sambillingham** [comment]
Any objection to me deploying this @samjbmason ?

**Comment by samjbmason** [comment]
Ah thats great was trying to grab a screenshot.

**Comment by samjbmason** [comment]
No objection to you depliying at all

**Comment by Sambillingham** [comment]
screen shot 2015-10-12 at 16 08 23

Some more thorough IE testing really wouldn't go a miss but I think it's good to get these fixed things out asap.

**Comment by Sambillingham** [comment]
Closes #65

**Pull request merged**
