### PR TITLE
content - blog post - sketch

### PR DESCRIPTION
**Pull request by Sambillingham**
Katies Sketch post 
sketch-design for developers beyond conference 2015 20151030

### CODE REVIEW

**Comment by katgrog** [comment]
What I see: Fourth paragraph reads, "template has you designing..." 

What I expect: Fourth paragraph reads "You can see why. Sketch has web design at its core. The web design template has you designing..."

**Comment by alicemollon** [comment]
What I see: Ending quotation mark at the end of the title
What I expect: Either a beginning quotation mark somewhere, or none at all

**Comment by Sambillingham** [comment]
sketch-design for developers beyond conference 2015 20151030

**Comment by Sambillingham** [comment]
Spoke to Chris yesterday - "Just read the blog post and it looks great! I’m not sure what to add, that’s a nice little summary. Perhaps a mention about exporting images? You can do it for different display densities in a couple of clicks!"  cc @katgrog

**Comment by Sambillingham** [comment]
Posting :)

**Pull request merged**
