### PR TITLE
Fix js missing on deploy

### PR DESCRIPTION
**Pull request by Sambillingham**
I think I narrowed down the issue of main.min.js file being deleted to the build task dependency.

### CODE REVIEW

**Comment by louisebishop1** [comment]
Well done buddy!

**Comment by Sambillingham** [comment]
From bcee04e8c393b640045bdeab09b65dd5b716973d  to 1c569280858997975dfab4fcf0061b4582a13a02 (Final commit/merge that includes the new dependency management along with the audio blog posts + alana post) there were issues deploying the site - We actually only tried to deploy this once 20th October - the site was missing a main.min.js file for 25mins. 

The difficulty was that the _site folder was built correctly but when using gh-pages task the files were not being generated in the .publish folder and not being pushed to github. I checkouted the project at a wide range of commits and discovered the fix above. I tested in a fork to be able to deploy and watch what happens.

**Comment by Sambillingham** [comment]
Lets see if it does the trick - if not we'll roll back to bcee04e8c393b640045bdeab09b65dd5b716973d again

**Comment by Sambillingham** [comment]
Did the trick :tada: deploying as per usual :smile:

**Pull request merged**
